name: Checks

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    name: "Run Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Run Test
        run: ./mvnw test
