name: CI

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup SDKMAN!
        uses: sdkman/sdkman-action@v1
        id: sdkman
      - name: Run Test
        run: ./mvnw -V -ntp verify
