name: Update Azul Zulu

on:
  schedule:
    - cron: 0 5 * * 1-5
  workflow_dispatch:

jobs:
  run:
    name: "Run Java Migration for Azul Zulu"
    strategy:
      fail-fast: false
      matrix:
        profile: [ zulu18linuxamd64, zulu18linuxarm64, zulu18macosamd64, zulu18macosarm64, zulu18windowsamd64,
                   zulu18fxlinuxamd64, zulu18fxlinuxarm64, zulu18fxmacosamd64, zulu18fxmacosarm64, zulu18fxwindowsamd64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-pom-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-pom-
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Run azul-zulu
        run: ./mvnw spring-boot:run -Dspring-boot.run.arguments="--spring.profiles.active=${{ matrix.profile }} --foojay.java.distribution=zulu"
        env:
          SDKMAN_RELEASE_CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          SDKMAN_RELEASE_CONSUMER_TOKEN: ${{ secrets.CONSUMER_TOKEN }}
