name: Update BellSoft Liberica

on:
  schedule:
    - cron: 0 5 * * 1-5
  workflow_dispatch:

jobs:
  run:
    name: "Run Java Migration for BellSoft Liberica"
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 18 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-pom-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-pom-
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Run bellsoft-liberica
        run: ./mvnw spring-boot:run -Dspring-boot.run.arguments="--foojay.java.distribution=liberica --foojay.java.version=${{ matrix.java-version }} --foojay.java.release-status=ga"
        env:
          SDKMAN_RELEASE_CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          SDKMAN_RELEASE_CONSUMER_TOKEN: ${{ secrets.CONSUMER_TOKEN }}
